name: chemicalelement
description: Periodic Table CRUD with SQLite + Provider
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.3
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/elements_seed.json

